package web

import (
	"embed"
	"io/fs"
)

// Assets contains the production frontend generated by Vite.
//
//go:embed dist/*
var assets embed.FS

func Assets() fs.FS {
	sub, err := fs.Sub(assets, "dist")
	if err != nil {
		panic(err)
	}
	return sub
}
